package main

import (
	"fmt"
	"math"
	"os"
	"strconv"

	colorful "github.com/lucasb-eyer/go-colorful"
)

// named color in hsl space
type nc struct {
	name string
	hu   float64
	sa   float64
	li   float64
}

var (
	h float64
	s float64
	l float64

	// define a slice of structs containig main hsl hues
	clrs = []nc{
		{"red", 0.0, 1.0, 0.5},
		{"orange", 0.0, 1.0, 0.5},
		{"yellow", 0.0, 1.0, 0.5},
		{"lime", 0.0, 1.0, 0.5},
		{"green", 0.0, 1.0, 0.5},
		{"teal", 0.0, 1.0, 0.5},
		{"cyan", 0.0, 1.0, 0.5},
		{"blue", 0.0, 1.0, 0.5},
		{"indigo", 0.0, 1.0, 0.5},
		{"violet", 0.0, 1.0, 0.5},
		{"fuschia", 0.0, 1.0, 0.5},
		{"pink", 0.0, 1.0, 0.5},
		{"grey", 0.0, 1.0, 0.5},
	}

	variants = []nc{}
)

func main() {
	// input color as CSS style hex
	ic := "#" + os.Args[1]

	// convert input to colorful.color as hex
	hc, _ := colorful.Hex(ic)

	// colorful.Color converted to hsl space (hue, saturation, lightness)
	h, s, l := hc.Hsl()

	//fmt.Println("Input color:", ic)
	//fmt.Println("Converted to HSL space:", h, s, l)

	// generate colors through 12 hue steps
	rotateHue(h, s, l)

	//generate a grey tinted with input (base) color
	grey(h, s, l)

	// generate 10 lightness level variants of each hue
	genVariants(h, s, l)

	// Output file with clrs as css vars
	// Open file for writing
	f, err := os.Create("colors.css")
	if err != nil {
		fmt.Printf("Error: %v\n", err)
	}
	// defers close file to when function finishes running
	defer f.Close()

	// start root section of css
	_, err = f.WriteString(`:root {
/* Generated by palegen */
`)
	if err != nil {
		fmt.Printf("Error: %v\n", err)
	}

	// Write the input base color directly as css vars
	_, err = fmt.Fprintf(f, "  --base: hsl(%1.f, %d%%, %d%%);\n", math.Floor(h), int(s*100), int(l*100))
	if err != nil {
		fmt.Printf("Error: %v", err)
	}

	// convert clrs slice to CSS output as css vars
	for i := range clrs {

		hs := int(clrs[i].sa * 100)
		hl := int(clrs[i].li * 100)
		fmt.Fprintf(f, "  --%s: hsl(%1.f, %d%%, %d%%);\n", clrs[i].name, clrs[i].hu, hs, hl)

		// TODO logic switch here based on command line flag for -hex vs --rgb vs default hsl
		//cv := colorful.Hsl(clrs[i].hu, clrs[i].sa, clrs[i].li)
		//r, g, b := cv.RGB255()
		//fmt.Fprintf(f, "  --%s: rgb(%d, %d, %d);\n", clrs[i].name, r, g, b)
		//hex := cv.Hex()
		//fmt.Fprintf(f, "  --%s: %v;\n", clrs[i].name, hex)
	}

	// black line in css
	_, err = fmt.Fprintf(f, "\n")
	if err != nil {
		fmt.Printf("Error: %v", err)
	}

	// Directly Add a black tinted to background via alpha
	_, err = f.WriteString("  --black: hsla(0, 100%, 0%, 0.9);\n")
	if err != nil {
		fmt.Printf("Error: %v", err)
	}

	// empty line
	_, err = f.WriteString("\n")
	if err != nil {
		fmt.Printf("Error: %v", err)
	}

	// Print lightness variants as CSS
	for i := range variants {
		s := int(variants[i].sa * 100)
		l := int(variants[i].li * 10)
		fmt.Fprintf(f, "  --%s: hsl(%1.f, %d%%, %d%%);\n", variants[i].name, variants[i].hu, s, l)
		//hex := cv.Hex()
		//fmt.Fprintf(f, "  --%s: %v;\n", variants[i].name, hex)
	}

	// end root section of css
	_, err = f.WriteString("\n}")
	if err != nil {
		fmt.Printf("Error: %v", err)
	}

	fmt.Println("Color generation complete.")

}

func rotateHue(h float64, s float64, l float64) []nc {

	// rotate the hue value around the full 360 degress with 12 steps
	steps := 12
	hueStep := float64(360 / steps)

	for i := 0; i < steps; i++ {

		h := math.Mod(((float64(i) * hueStep) + h), 360)

		switch {
		case h >= 350 && h <= 360:
			for i := range clrs {
				if clrs[i].name == "red" {
					clrs[i].hu = math.Floor(h)
					clrs[i].sa = s
					clrs[i].li = l
				}
			}
		case h >= 0 && h <= 20:
			for i := range clrs {
				if clrs[i].name == "red" {
					clrs[i].hu = math.Floor(h)
					clrs[i].sa = s
					clrs[i].li = l
				}
			}
		case h > 20 && h <= 50:
			for i := range clrs {
				if clrs[i].name == "orange" {
					clrs[i].hu = math.Floor(h)
					clrs[i].sa = s
					clrs[i].li = l
				}
			}
		case h > 50 && h <= 80:
			for i := range clrs {
				if clrs[i].name == "yellow" {
					clrs[i].hu = math.Floor(h)
					clrs[i].sa = s
					clrs[i].li = l
				}
			}
		case h > 80 && h <= 110:
			for i := range clrs {
				if clrs[i].name == "lime" {
					clrs[i].hu = math.Floor(h)
					clrs[i].sa = s
					clrs[i].li = l
				}
			}
		case h > 110 && h <= 140:
			for i := range clrs {
				if clrs[i].name == "green" {
					clrs[i].hu = math.Floor(h)
					clrs[i].sa = s
					clrs[i].li = l
				}
			}
		case h > 140 && h <= 170:
			for i := range clrs {
				if clrs[i].name == "teal" {
					clrs[i].hu = math.Floor(h)
					clrs[i].sa = s
					clrs[i].li = l
				}
			}
		case h > 170 && h <= 200:
			for i := range clrs {
				if clrs[i].name == "cyan" {
					clrs[i].hu = math.Floor(h)
					clrs[i].sa = s
					clrs[i].li = l
				}
			}
		case h > 200 && h <= 230:
			for i := range clrs {
				if clrs[i].name == "blue" {
					clrs[i].hu = math.Floor(h)
					clrs[i].sa = s
					clrs[i].li = l
				}
			}
		case h > 230 && h <= 260:
			for i := range clrs {
				if clrs[i].name == "indigo" {
					clrs[i].hu = math.Floor(h)
					clrs[i].sa = s
					clrs[i].li = l
				}
			}
		case h > 260 && h <= 290:
			for i := range clrs {
				if clrs[i].name == "violet" {
					clrs[i].hu = math.Floor(h)
					clrs[i].sa = s
					clrs[i].li = l
				}
			}
		case h > 290 && h <= 320:
			for i := range clrs {
				if clrs[i].name == "fuschia" {
					clrs[i].hu = math.Floor(h)
					clrs[i].sa = s
					clrs[i].li = l
				}
			}
		case h > 320 && h <= 350:
			for i := range clrs {
				if clrs[i].name == "pink" {
					clrs[i].hu = math.Floor(h)
					clrs[i].sa = s
					clrs[i].li = l
				}
			}
		}
	}
	return clrs
}

func grey(h float64, s float64, l float64) []nc {

	ns := (s + 0.4) / 10

	for i := range clrs {
		if clrs[i].name == "grey" {
			clrs[i].hu = math.Floor(h)
			clrs[i].sa = ns
			clrs[i].li = 0.7
		}
	}
	return clrs
}

func genVariants(h float64, s float64, l float64) []nc {

	// step through fixed lightness values
	lightness := [10]float64{9.5, 8.7, 7.8, 6.9, 6, 5.1, 4.2, 3.3, 2.4, 1.5}

	for x := range clrs {
		for i := 0; i < len(lightness); i++ {
			nnc := new(nc)
			nnc.name = clrs[x].name + strconv.Itoa(i)
			nnc.hu = clrs[x].hu
			nnc.sa = clrs[x].sa
			nnc.li = lightness[i]
			variants = append(variants, *nnc)
		}
	}
	return variants

}
